include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - example/**
    - example/adaptative_theme_example/**
    - example/argo_example/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"


  errors:
    sort_unnamed_constructors_first: ignore
    avoid_redundant_argument_values: ignore
    constant_identifier_names: ignore
    avoid_positional_boolean_parameters: ignore
    prefer_initializing_formals: ignore
    
    